/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.54
 * Generated at: 2026-04-12 09:25:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import com.fda.model.Cart;
import com.fda.model.CartItem;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1775984998000L));
    _jspx_dependants.put("jar:file:/D:/app/tools/apache-tomcat-10.1.54/webapps/food-delivery/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.fda.model.Cart");
    _jspx_imports_classes.add("com.fda.model.CartItem");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Your Cart | UrbanEats</title>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: Arial, sans-serif;\r\n");
      out.write("        background-color: #f5f5f5;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ===== HEADER ===== */\r\n");
      out.write("    header {\r\n");
      out.write("        position: sticky;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: space-between;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        padding: 15px 40px;\r\n");
      out.write("        background: #2c3e50;\r\n");
      out.write("        color: white;\r\n");
      out.write("        z-index: 100;\r\n");
      out.write("        box-shadow: 0 2px 6px rgba(0,0,0,0.2);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    header h1 {\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size: 28px;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .nav-buttons {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        gap: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown {\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropbtn {\r\n");
      out.write("        background: #34495e;\r\n");
      out.write("        padding: 8px 16px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        color: white;\r\n");
      out.write("        transition: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropbtn:hover {\r\n");
      out.write("        background: #3d5a73;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-content {\r\n");
      out.write("        display: none;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 100%;\r\n");
      out.write("        left: 0;\r\n");
      out.write("        background: white;\r\n");
      out.write("        min-width: 140px;\r\n");
      out.write("        box-shadow: 0 4px 10px rgba(0,0,0,0.2);\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-content a {\r\n");
      out.write("        padding: 10px;\r\n");
      out.write("        display: block;\r\n");
      out.write("        color: #333;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        transition: 0.2s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown-content a:hover {\r\n");
      out.write("        background: #f1f1f1;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .dropdown:hover .dropdown-content {\r\n");
      out.write("        display: block;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cart a {\r\n");
      out.write("        background: #e67e22;\r\n");
      out.write("        padding: 8px 14px;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        color: white;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        transition: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .cart a:hover {\r\n");
      out.write("        background: #d35400;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-btn, .signup-btn {\r\n");
      out.write("        background: #27ae60;\r\n");
      out.write("        padding: 8px 14px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        color: white;\r\n");
      out.write("        transition: 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .login-btn:hover, .signup-btn:hover {\r\n");
      out.write("        background: #1e8449;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /* ===== CART CONTAINER ===== */\r\n");
      out.write("    .container {\r\n");
      out.write("        width: 90%;\r\n");
      out.write("        margin: 40px auto;\r\n");
      out.write("        background: #fff;\r\n");
      out.write("        padding: 30px;\r\n");
      out.write("        border-radius: 10px;\r\n");
      out.write("        box-shadow: 0 2px 10px rgba(0,0,0,0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    h2 {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 25px;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    table {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        border-collapse: collapse;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    th, td {\r\n");
      out.write("        padding: 12px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        border-bottom: 1px solid #eee;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    th {\r\n");
      out.write("        background: #ecf0f1;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    img.cart-img {\r\n");
      out.write("        width: 90px;\r\n");
      out.write("        height: 70px;\r\n");
      out.write("        object-fit: cover;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn {\r\n");
      out.write("        padding: 6px 10px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 4px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size: 14px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-inc { background: #2ecc71; color: white; }\r\n");
      out.write("    .btn-dec { background: #f39c12; color: white; }\r\n");
      out.write("    .btn-del { background: #e74c3c; color: white; }\r\n");
      out.write("    .btn-inc:hover { background: #27ae60; }\r\n");
      out.write("    .btn-dec:hover { background: #d68910; }\r\n");
      out.write("    .btn-del:hover { background: #c0392b; }\r\n");
      out.write("\r\n");
      out.write("    .quantity-controls form {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        margin: 0 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .quantity-controls strong {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        vertical-align: middle;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .total-section {\r\n");
      out.write("        text-align: right;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        color: #2c3e50;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .action-buttons {\r\n");
      out.write("        text-align: right;\r\n");
      out.write("        margin-top: 15px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .action-buttons form {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .empty-msg {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        color: #7f8c8d;\r\n");
      out.write("        font-size: 18px;\r\n");
      out.write("        padding: 40px 0;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- ✅ SINGLE HEADER -->\r\n");
      out.write("<header>\r\n");
      out.write("    <h1 onclick=\"window.location.href='home'\">UrbanEats</h1>\r\n");
      out.write("    <div class=\"nav-buttons\">\r\n");
      out.write("        ");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<!-- ✅ CART CONTENT -->\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("    <h2>Your Cart</h2>\r\n");
      out.write("\r\n");
      out.write("    ");

        Cart cart = (Cart) session.getAttribute("cart");
        if (cart == null || cart.getItems() == null || cart.getItems().isEmpty()) {
    
      out.write("\r\n");
      out.write("        <p class=\"empty-msg\">Your cart is empty.</p>\r\n");
      out.write("    ");

        } else {
            double total = 0.0;
            Collection<CartItem> items = cart.getItems();
    
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <table>\r\n");
      out.write("        <thead>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th>Image</th>\r\n");
      out.write("                <th>Item</th>\r\n");
      out.write("                <th>Price (₹)</th>\r\n");
      out.write("                <th>Quantity</th>\r\n");
      out.write("                <th>Subtotal (₹)</th>\r\n");
      out.write("                <th>Action</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </thead>\r\n");
      out.write("        <tbody>\r\n");
      out.write("        ");

            for (CartItem item : items) {
                double subtotal = item.getPrice() * item.getQuantity();
                total += subtotal;
        
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td><img class=\"cart-img\" src=\"");
      out.print( (item.getImagePath() != null && !item.getImagePath().isEmpty()) ? item.getImagePath() : "images/placeholder.png" );
      out.write("\" alt=\"image\"></td>\r\n");
      out.write("                <td>");
      out.print( item.getName() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( String.format("%.2f", item.getPrice()) );
      out.write("</td>\r\n");
      out.write("                <td class=\"quantity-controls\">\r\n");
      out.write("                    <form action=\"cart\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"decrease\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"itemId\" value=\"");
      out.print( item.getId() );
      out.write("\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-dec\" ");
      out.print( (item.getQuantity() == 1) ? "disabled" : "" );
      out.write(">−</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                    <strong>");
      out.print( item.getQuantity() );
      out.write("</strong>\r\n");
      out.write("                    <form action=\"cart\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"increase\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"itemId\" value=\"");
      out.print( item.getId() );
      out.write("\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-inc\">+</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>");
      out.print( String.format("%.2f", subtotal) );
      out.write("</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                    <form action=\"cart\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"remove\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"itemId\" value=\"");
      out.print( item.getId() );
      out.write("\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-del\">Remove</button>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        ");

            } // end for
        
      out.write("\r\n");
      out.write("        </tbody>\r\n");
      out.write("    </table>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"total-section\">\r\n");
      out.write("        <h3>Total: ₹");
      out.print( String.format("%.2f", total) );
      out.write("</h3>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"action-buttons\">\r\n");
      out.write("        <form action=\"checkout\" method=\"get\">\n");
      out.write("            <button type=\"submit\" class=\"btn btn-inc\" style=\"padding:10px 20px;\">Proceed to Checkout</button>\r\n");
      out.write("        </form>\r\n");
      out.write("        <form action=\"MenuServlet\" method=\"get\">\r\n");
      out.write("            <input type=\"hidden\" name=\"restaurantId\" value=\"");
      out.print( session.getAttribute("restaurantId") );
      out.write("\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn\" style=\"background:#3498db; color:white; padding:10px 20px;\">Add More Items</button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    ");

        } // end else
    
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /cart.jsp(214,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.currentUser}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <div class=\"dropdown\">\r\n");
          out.write("                    <button class=\"dropbtn\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.currentUser.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" ▼</button>\r\n");
          out.write("                    <div class=\"dropdown-content\">\r\n");
          out.write("                        <a href=\"logout\">Logout</a>\r\n");
          out.write("                    </div>\r\n");
          out.write("                </div>\r\n");
          out.write("                <div class=\"cart\">\r\n");
          out.write("                    <a href=\"cart.jsp\">\r\n");
          out.write("                        🛒 Cart\r\n");
          out.write("                        ");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                    </a>\r\n");
          out.write("                </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /cart.jsp(224,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty sessionScope.cartCount}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                            (");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.cartCount}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <button class=\"login-btn\" onclick=\"window.location.href='login.html'\">Login</button>\r\n");
          out.write("                <button class=\"signup-btn\" onclick=\"window.location.href='register.html'\">Sign Up</button>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    }
    return false;
  }
}
